package com.kiteclass.core.module.clazz.entity;

import com.kiteclass.core.common.constant.ClassStatus;
import com.kiteclass.core.common.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Class entity representing a specific instance of a course.
 *
 * <p>A class is a concrete learning event within a course, with:
 * <ul>
 *   <li>Schedule and location details</li>
 *   <li>Student capacity management</li>
 *   <li>Class code for self-enrollment</li>
 *   <li>Lifecycle: SCHEDULED → IN_PROGRESS → COMPLETED</li>
 * </ul>
 *
 * <p>Business Rules:
 * <ul>
 *   <li>BR-CLASS-001: Must belong to an existing non-ARCHIVED course</li>
 *   <li>BR-CLASS-003: current_enrolled <= max_students</li>
 *   <li>BR-CLASS-004: class_code must be unique (when set)</li>
 *   <li>BR-CLASS-005: end_date > start_date (when both provided)</li>
 *   <li>BR-CLASS-006: Schedule editable only when SCHEDULED</li>
 * </ul>
 *
 * @author KiteClass Team
 * @since 2.5.0
 */
@Entity
@Table(
        name = "classes",
        indexes = {
                @Index(name = "idx_classes_course_id", columnList = "course_id"),
                @Index(name = "idx_classes_status", columnList = "status"),
                @Index(name = "idx_classes_start_date", columnList = "start_date"),
                @Index(name = "idx_classes_instance_id", columnList = "instance_id"),
                @Index(name = "idx_classes_deleted", columnList = "deleted")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Class extends BaseEntity {

    /**
     * Foreign key to the parent course.
     * Required, must reference an existing non-ARCHIVED course.
     */
    @Column(name = "course_id", nullable = false)
    private Long courseId;

    /**
     * Foreign key to the teacher who owns this class.
     *
     * <p>Set at creation time from the caller's user context (X-User-Id when the caller is a TEACHER).
     * Drives {@code AuthorizationBean.hasAccessToClass()} guard — teacher can only access classes
     * where {@code teacher_id = currentUserId}.
     *
     * <p>Schema: column already exists in V1__create_core_schema.sql line 158 (`teacher_id BIGINT REFERENCES teachers(id)`).
     * Pre-GAP-727 the entity did NOT map this column → JPA never persisted it → every teacher locked out (NOT IDOR, full lock-out).
     *
     * <p>Nullable for legacy classes created before GAP-727 fix + classes created by ADMIN role (no single teacher owner).
     *
     * @since GAP-727 Wave beta-readiness-2 Bucket B
     */
    @Column(name = "teacher_id")
    private Long teacherId;

    /**
     * Class name.
     * Required, 5-200 characters.
     * Example: "English B1 - Evening Mon-Wed-Fri"
     * Must be unique within the same course and tenant.
     */
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /**
     * Class description.
     * Optional, max 2000 characters.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Human-readable schedule text.
     * Optional, max 200 characters.
     * Example: "Mon-Wed-Fri 18:00-20:00"
     */
    @Column(name = "schedule", length = 200)
    private String schedule;

    /**
     * Structured recurrence rule (RFC 5545 RRULE subset) — GAP-290 Wave 18a.
     *
     * <p>Stored as JSONB. When non-null, sessions are auto-generated by
     * {@code RecurrenceService}. Schema (v1):
     * <pre>{
     *   "freq": "WEEKLY",
     *   "by_day": ["TU", "TH"],
     *   "start_time": "19:00",
     *   "end_time": "20:30",
     *   "until": "2026-08-01",
     *   "exclude_dates": ["2026-06-15"]
     * }</pre>
     *
     * <p>Stored as a String here for backwards-compatibility with
     * {@link com.fasterxml.jackson.databind.ObjectMapper} serialization in the
     * service layer; bind path uses {@link SqlTypes#JSON} per
     * {@code feedback_jpa_jsonb_jdbctypecode.md}.
     *
     * @since GAP-290 Wave 18a
     */
    @Column(name = "recurrence_rule", columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private String recurrenceRule;

    /**
     * Location type: IN_PERSON or ONLINE.
     * Required, defaults to IN_PERSON.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "location_type", nullable = false, length = 20)
    @Builder.Default
    private LocationType locationType = LocationType.IN_PERSON;

    /**
     * Location detail.
     * Optional, max 200 characters.
     * Example: "Room 101" or "https://zoom.us/j/123456"
     */
    @Column(name = "location_detail", length = 200)
    private String locationDetail;

    /**
     * Class start date.
     * Optional. When set, must be before end_date.
     */
    @Column(name = "start_date")
    private LocalDate startDate;

    /**
     * Class end date.
     * Optional. When set, must be after start_date.
     */
    @Column(name = "end_date")
    private LocalDate endDate;

    /**
     * Maximum number of students allowed.
     * Required, defaults to 30, must be >= 1.
     */
    @Column(name = "max_students", nullable = false)
    @Builder.Default
    private Integer maxStudents = 30;

    /**
     * Current number of active enrolled students.
     * Managed automatically, starts at 0.
     * Must be <= max_students.
     */
    @Column(name = "current_enrolled", nullable = false)
    @Builder.Default
    private Integer currentEnrolled = 0;

    /**
     * Unique class code for student self-enrollment.
     * Optional, 6-20 uppercase alphanumeric characters.
     * Example: "ABC123XY"
     */
    @Column(name = "class_code", length = 20)
    private String classCode;

    /**
     * Expiry timestamp for the class code.
     * After this time, students cannot use the code to enroll.
     */
    @Column(name = "code_expires_at")
    private Instant codeExpiresAt;

    /**
     * Lifecycle status of the class.
     * SCHEDULED → IN_PROGRESS → COMPLETED
     *         ↓
     *      CANCELLED
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private ClassStatus status = ClassStatus.SCHEDULED;

    /**
     * Timestamp when class transitioned to IN_PROGRESS.
     */
    @Column(name = "started_at")
    private Instant startedAt;

    /**
     * Timestamp when class transitioned to COMPLETED.
     */
    @Column(name = "completed_at")
    private Instant completedAt;

    /**
     * Timestamp when class transitioned to CANCELLED.
     */
    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    // =========================================================================
    // Reschedule audit columns (Wave beta-readiness-4 Bucket D — GAP-291)
    // =========================================================================

    /**
     * User ID who triggered the most recent reschedule operation.
     * Null when class has never been rescheduled.
     */
    @Column(name = "rescheduled_by_user_id")
    private Long rescheduledByUserId;

    /**
     * Timestamp of the most recent reschedule operation (UTC).
     * Null when class has never been rescheduled.
     */
    @Column(name = "rescheduled_at")
    private Instant rescheduledAt;

    /**
     * startDate captured BEFORE the most recent reschedule (audit trail).
     */
    @Column(name = "previous_start_date")
    private LocalDate previousStartDate;

    /**
     * endDate captured BEFORE the most recent reschedule (audit trail).
     */
    @Column(name = "previous_end_date")
    private LocalDate previousEndDate;

    /**
     * Reason category for the most recent reschedule.
     * Stored as VARCHAR; deserialized as {@code RescheduleReasonCategory} enum at service layer.
     */
    @Column(name = "reschedule_reason_category", length = 64)
    private String rescheduleReasonCategory;

    /**
     * Optional free-text notes for the most recent reschedule (max 2000 chars).
     */
    @Column(name = "reschedule_reason_notes", columnDefinition = "TEXT")
    private String rescheduleReasonNotes;

    // =========================================================================
    // Business Logic Methods
    // =========================================================================

    /**
     * Checks if the class can accept new enrollments.
     *
     * @return true if status is SCHEDULED or IN_PROGRESS and not at capacity
     */
    public boolean canEnroll() {
        return (status == ClassStatus.SCHEDULED || status == ClassStatus.IN_PROGRESS)
                && currentEnrolled < maxStudents;
    }

    /**
     * Checks if the schedule can be modified.
     * Schedule is locked once class transitions to IN_PROGRESS.
     *
     * @return true if class is SCHEDULED
     */
    public boolean canEditSchedule() {
        return status == ClassStatus.SCHEDULED;
    }

    /**
     * Checks if the class can be started.
     *
     * @return true if status is SCHEDULED
     */
    public boolean canStart() {
        return status == ClassStatus.SCHEDULED;
    }

    /**
     * Checks if the class can be completed.
     *
     * @return true if status is IN_PROGRESS
     */
    public boolean canComplete() {
        return status == ClassStatus.IN_PROGRESS;
    }

    /**
     * Checks if the class can be cancelled.
     *
     * @return true if status is SCHEDULED or IN_PROGRESS
     */
    public boolean canCancel() {
        return status == ClassStatus.SCHEDULED || status == ClassStatus.IN_PROGRESS;
    }

    /**
     * Checks if the class can be deleted.
     * Only SCHEDULED classes with no enrolled students can be deleted.
     *
     * @return true if SCHEDULED with 0 enrollments
     */
    public boolean canDelete() {
        return status == ClassStatus.SCHEDULED && currentEnrolled == 0;
    }

    /**
     * Checks if class code is valid (not expired).
     *
     * @return true if code exists and is not expired
     */
    public boolean isCodeValid() {
        if (classCode == null) {
            return false;
        }
        if (codeExpiresAt == null) {
            return true;
        }
        return Instant.now().isBefore(codeExpiresAt);
    }

    /**
     * Location type for a class.
     *
     * <p>Determines whether the class is held in person or online.
     */
    public enum LocationType {

        IN_PERSON("Trực tiếp", "Class held in physical classroom"),
        ONLINE("Trực tuyến", "Class held online via video conference");

        private final String displayNameVi;
        private final String description;

        LocationType(String displayNameVi, String description) {
            this.displayNameVi = displayNameVi;
            this.description = description;
        }

        /**
         * Returns Vietnamese display name.
         *
         * @return display name in Vietnamese
         */
        public String getDisplayNameVi() {
            return displayNameVi;
        }

        /**
         * Returns description of this location type.
         *
         * @return description
         */
        public String getDescription() {
            return description;
        }
    }
}
