#!/bin/bash
# KiteHub Scripts Help
# Usage: ./scripts/help.sh

echo "=============================================="
echo "  KiteHub Docker Scripts"
echo "=============================================="
echo ""
echo "Build & Deploy:"
echo "  ./scripts/build-all.sh [--no-cache]   Build all images (base first)"
echo "  ./scripts/rebuild.sh <svc> [--no-cache] Rebuild single service"
echo "  ./scripts/up.sh [service...]          Start stack or specific services"
echo "  ./scripts/down.sh [--volumes]         Stop stack (optionally remove data)"
echo "  ./scripts/restart.sh [service...]     Restart service(s)"
echo ""
echo "Monitoring:"
echo "  ./scripts/status.sh [--health]        Show status and URLs"
echo "  ./scripts/logs.sh [service] [-f]      View logs (follow with -f)"
echo ""
echo "Maintenance:"
echo "  ./scripts/exec.sh <service> [cmd]     Execute command in container"
echo "  ./scripts/clean.sh [--all]            Cleanup (--all removes everything)"
echo ""
echo "=============================================="
echo "  Services"
echo "=============================================="
echo ""
echo "  Backend:  gateway, subscription, branding, email, admin"
echo "  Frontend: frontend"
echo "  Infra:    postgres, redis, rabbitmq, minio"
echo ""
echo "=============================================="
echo "  Quick Start"
echo "=============================================="
echo ""
echo "  1. Build:    ./scripts/build-all.sh"
echo "  2. Start:    ./scripts/up.sh"
echo "  3. Status:   ./scripts/status.sh --health"
echo "  4. Logs:     ./scripts/logs.sh gateway -f"
echo "  5. Stop:     ./scripts/down.sh"
echo ""
