-- DEPRECATED (GAP-1196, 2026-06-11) — KHÔNG chạy file này.
--
-- Landing sections (teachers / pricing_tiers / stats / hero / template_type /
-- centerName / F-sections) cho demo tenants giờ do MỘT nguồn canonical seed:
--   kiteclass-core BrandingDataSeeder (@Profile dev) — upsert idempotent mỗi boot,
--   số liệu academic-accurate khớp DemoAcademicSeeder (Hà 12HV/85%, Nhì 35HV/94%).
--
-- File SQL one-off này từng giữ giá trị marketing bịa (500+ học sinh / 95%) mâu
-- thuẫn seeder → mọi UPDATE đã gỡ. Giữ file làm tombstone tránh vỡ reference;
-- cần chỉnh demo landing content → sửa BrandingDataSeeder constants rồi rebuild
-- kiteclass-core (cache landingPages tự evict per GAP-1203).
