#!/bin/bash
#
# KiteHub Local Development Setup
# One command to set up the entire stack
#
# Usage: ./scripts/setup.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m"

echo ""
echo "=============================================="
echo "  KiteHub Local Development Setup"
echo "=============================================="
echo ""

# ============================================================
# Step 1: Generate .env file
# ============================================================
ENV_FILE="$PROJECT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}[1/4]${NC} .env file already exists. Skipping generation."
  echo "       Delete .env and re-run to regenerate."
else
  echo -e "${GREEN}[1/4]${NC} Generating .env file with secure random values..."

  # GAP-417: openssl rand -base64 wraps at 64 chars with embedded \n; the newline
  # gets written into .env as a line break, causing docker-compose to parse the
  # remainder as a new variable name with invalid chars (e.g. "FqXo/qnAZaqwQ").
  # Strip newlines + chars that conflict with shell parsing on the env-var path.
  DEV_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
  ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n=/+')
  JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n=/+')
  INTERNAL_SECRET=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

  cat > "$ENV_FILE" <<EOF
# =============================================================================
# KiteHub Local Development - Auto-generated by setup.sh
# Generated: $(date -Iseconds)
# =============================================================================

# --- Database ---
POSTGRES_USER=kitehub
POSTGRES_PASSWORD=${DEV_PASSWORD}
POSTGRES_DB=kitehub

# --- RabbitMQ ---
RABBITMQ_USER=kitehub
RABBITMQ_PASSWORD=${DEV_PASSWORD}

# --- MinIO ---
MINIO_ROOT_USER=kitehub
MINIO_ROOT_PASSWORD=${DEV_PASSWORD}

# --- Security ---
ENCRYPTION_MASTER_KEY=${ENCRYPTION_KEY}
JWT_SECRET=${JWT_SECRET}
INTERNAL_API_SECRET=${INTERNAL_SECRET}

# --- OpenAI (mock mode for local dev) ---
OPENAI_API_KEY=sk-mock-key
EOF

  echo "       .env file created with unique passwords."
fi

# ============================================================
# Step 2: Build all images
# ============================================================
echo ""
echo -e "${GREEN}[2/4]${NC} Building Docker images..."
cd "$PROJECT_DIR"
./scripts/build-all.sh 2>&1 | tail -5

# ============================================================
# Step 3: Start stack
# ============================================================
echo ""
echo -e "${GREEN}[3/4]${NC} Starting all services..."
./scripts/up.sh 2>&1 | tail -10

# ============================================================
# Step 4: Wait for health
# ============================================================
echo ""
echo -e "${GREEN}[4/4]${NC} Waiting for services to be healthy..."

SERVICES="9000 8081 8085 8083 8088 3001"
ALL_READY=true

for PORT in $SERVICES; do
  printf "       Port %s: " "$PORT"
  READY=false
  for i in $(seq 1 30); do
    if curl -sf "http://localhost:$PORT/actuator/health" > /dev/null 2>&1 || \
       curl -sf "http://localhost:$PORT/api/health" > /dev/null 2>&1 || \
       curl -sf "http://localhost:$PORT" > /dev/null 2>&1; then
      echo "ready"
      READY=true
      break
    fi
    sleep 2
  done
  if [ "$READY" = false ]; then
    echo "TIMEOUT (may still be starting)"
    ALL_READY=false
  fi
done

# ============================================================
# Done
# ============================================================
echo ""
echo "=============================================="
echo "  Setup Complete!"
echo "=============================================="
echo ""
echo "  URLs:"
echo "    Frontend:    http://localhost:3001"
echo "    Gateway:     http://localhost:9000"
echo "    KiteClass:   http://localhost:8088"
echo ""
echo "  Next steps:"
echo "    1. Seed test data:  ./scripts/seed-data.sh"
echo "    2. Run API tests:   ./scripts/test-api-e2e.sh"
echo "    3. View logs:       ./scripts/logs.sh <service>"
echo ""
