#!/bin/bash
#
# KiteHub Local Development Setup
# One command to set up the entire stack
#
# Usage: ./scripts/setup.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# GAP-694 Phase 0B preflight: verify Docker daemon reachable before bootstrap.
bash "$SCRIPT_DIR/check-docker.sh" || { echo "[setup.sh] Docker preflight failed. See output above." >&2; exit 1; }

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

echo ""
echo "=============================================="
echo "  KiteHub Local Development Setup"
echo "=============================================="
echo ""

# ============================================================
# Step 1: Generate .env file
# ============================================================
ENV_FILE="$PROJECT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}[1/4]${NC} .env file already exists. Skipping generation."
  echo "       Delete .env and re-run to regenerate."
else
  echo -e "${GREEN}[1/4]${NC} Generating .env file with secure random values..."

  # GAP-417 + GAP-426: openssl rand -base64 wraps at 64 chars with embedded \n.
  # GAP-417 stripped \n=/+ which corrupted base64 (= is padding, /+ are valid
  # base64 chars). EncryptionService strict 32-byte decode then crashed.
  # Fix per GAP-426: strip newline only; quote in env template for shell safety.
  DEV_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
  ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')
  JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
  INTERNAL_SECRET=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

  cat > "$ENV_FILE" <<EOF
# =============================================================================
# KiteHub Local Development - Auto-generated by setup.sh
# Generated: $(date -Iseconds)
# =============================================================================

# --- Database ---
POSTGRES_USER=kitehub
POSTGRES_PASSWORD=${DEV_PASSWORD}
POSTGRES_DB=kitehub

# --- RabbitMQ ---
RABBITMQ_USER=kitehub
RABBITMQ_PASSWORD=${DEV_PASSWORD}

# --- MinIO ---
MINIO_ROOT_USER=kitehub
MINIO_ROOT_PASSWORD=${DEV_PASSWORD}

# --- Security --- (quoted per GAP-426 to protect base64 +/= chars from shell parsing)
ENCRYPTION_MASTER_KEY="${ENCRYPTION_KEY}"
JWT_SECRET="${JWT_SECRET}"
INTERNAL_API_SECRET="${INTERNAL_SECRET}"

# --- OpenAI (mock mode for local dev) ---
OPENAI_API_KEY=sk-mock-key
EOF

  echo "       .env file created with unique passwords."

  # GAP-426 self-test: verify ENCRYPTION_MASTER_KEY decodes to exactly 32 bytes.
  KEY_VAL=$(grep '^ENCRYPTION_MASTER_KEY=' "$ENV_FILE" | sed 's/^[^=]*=//; s/^"//; s/"$//')
  KEY_BYTES=$(printf '%s' "$KEY_VAL" | base64 -d 2>/dev/null | wc -c)
  if [ "$KEY_BYTES" != "32" ]; then
    echo -e "${RED}[FAIL]${NC} ENCRYPTION_MASTER_KEY base64 decode = $KEY_BYTES bytes, expected 32. (GAP-426)"
    exit 1
  fi
fi

# ============================================================
# Step 2: Build all images
# ============================================================
echo ""
echo -e "${GREEN}[2/4]${NC} Building Docker images..."
cd "$PROJECT_DIR"
./scripts/build-all.sh 2>&1 | tail -5

# ============================================================
# Step 3: Start stack
# ============================================================
echo ""
echo -e "${GREEN}[3/4]${NC} Starting all services..."
./scripts/up.sh 2>&1 | tail -10

# ============================================================
# Step 4: Wait for health
# ============================================================
echo ""
echo -e "${GREEN}[4/4]${NC} Waiting for services to be healthy..."

SERVICES="9000 8081 8085 8083 8088 3001"
ALL_READY=true

for PORT in $SERVICES; do
  printf "       Port %s: " "$PORT"
  READY=false
  for i in $(seq 1 30); do
    if curl -sf "http://localhost:$PORT/actuator/health" > /dev/null 2>&1 || \
       curl -sf "http://localhost:$PORT/api/health" > /dev/null 2>&1 || \
       curl -sf "http://localhost:$PORT" > /dev/null 2>&1; then
      echo "ready"
      READY=true
      break
    fi
    sleep 2
  done
  if [ "$READY" = false ]; then
    echo "TIMEOUT (may still be starting)"
    ALL_READY=false
  fi
done

# ============================================================
# Done
# ============================================================
echo ""
echo "=============================================="
echo "  Setup Complete!"
echo "=============================================="
echo ""
echo "  URLs:"
echo "    Frontend:    http://localhost:3001"
echo "    Gateway:     http://localhost:9000"
echo "    KiteClass:   http://localhost:8088"
echo ""
echo "  Next steps:"
echo "    1. Seed test data:  ./scripts/seed-data.sh"
echo "    2. Run API tests:   ./scripts/test-api-e2e.sh"
echo "    3. View logs:       ./scripts/logs.sh <service>"
echo ""
