apiVersion: v1
kind: ConfigMap
metadata:
  name: kitehub-config
  namespace: kitehub
data:
  # Database
  database.host: "kitehub-postgres.kitehub.svc.cluster.local"
  database.port: "5432"
  database.name: "kitehub"

  # RabbitMQ
  rabbitmq.host: "kitehub-rabbitmq.kitehub.svc.cluster.local"
  rabbitmq.port: "5672"

  # Redis
  redis.host: "kitehub-redis.kitehub.svc.cluster.local"
  redis.port: "6379"

  # AWS
  aws.region: "ap-southeast-1"
  s3.bucket: "kitehub-assets"

  # OpenAI
  openai.base-url: "https://api.openai.com/v1"

  # Application
  spring.profiles.active: "production"
