global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "kiteclass-core"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["core:8081"]
