package com.kitehub.branding.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Landing page content generated by AI.
 *
 * @since 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LandingPageContent {

    /**
     * Hero section title (max 60 chars).
     * Example: "Trung Tâm Tiếng Anh Hàng Đầu Việt Nam"
     */
    private String heroTitle;

    /**
     * Hero section subtitle (max 150 chars).
     * Example: "Phương pháp học hiện đại, giáo viên giàu kinh nghiệm, cam kết đầu ra"
     */
    private String heroSubtitle;

    /**
     * Brand tagline (max 30 chars).
     * Example: "Học Vui, Tiến Xa"
     */
    private String tagline;

    /**
     * About Us section (3 paragraphs).
     */
    private String aboutUs;

    /**
     * Mission statement (1-2 sentences).
     */
    private String mission;

    /**
     * Vision statement (1-2 sentences).
     */
    private String vision;

    /**
     * List of feature highlights (3-5 features).
     */
    private List<Feature> features;

    /**
     * Call-to-action text (max 40 chars).
     * Example: "Đăng Ký Học Thử Miễn Phí"
     */
    private String ctaText;
}
