package com.kiteclass.core.module.student.bulkimport.service;

import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

/**
 * Generates the blank "import template" xlsx (GAP-1102).
 *
 * <p>Users download this template so they know the EXACT column headers + format
 * before filling in their data. The template has two sheets:
 * <ul>
 *   <li><b>HocVien</b> — sheet 0: header row (7 canonical columns, bold + frozen)
 *       followed by 2 example data rows with Vietnamese sample values.</li>
 *   <li><b>HuongDan</b> — sheet 1: per-column instructions (required/optional +
 *       format rule) mirroring BR-BI-010..015.</li>
 * </ul>
 *
 * <p><b>Canonical headers (MUST stay in sync with {@link XlsxParser} COL_*
 * constants):</b>
 * <pre>
 *   name | email | phone | date_of_birth | gender | address | note
 * </pre>
 * Required: {@code name}, {@code email}. Others optional. The header row is built
 * directly from {@link XlsxParser#COL_NAME} .. {@link XlsxParser#COL_NOTE} so a
 * column rename in the parser forces a compile-time update here too.
 *
 * <p>Output is tenant-agnostic / static — same bytes for every caller. Round-trip
 * guarantee: feeding the generated bytes back into {@link XlsxParser#parse} parses
 * cleanly, and the 2 example rows pass {@link RowValidator} with zero errors (so
 * users can copy the pattern safely).
 *
 * @author KiteClass Team
 * @since 3.x (GAP-1102)
 */
@Slf4j
@Component
public class XlsxTemplateGenerator {

    /** Sheet 1 — fill-in data sheet (parser reads sheet index 0). */
    private static final String DATA_SHEET_NAME = "HocVien";

    /** Sheet 2 — Vietnamese instructions. */
    private static final String GUIDE_SHEET_NAME = "HuongDan";

    /**
     * Canonical header order. References {@link XlsxParser} COL_* constants so the
     * template never drifts from what the parser expects.
     */
    private static final String[] HEADERS = {
            XlsxParser.COL_NAME,
            XlsxParser.COL_EMAIL,
            XlsxParser.COL_PHONE,
            XlsxParser.COL_DOB,
            XlsxParser.COL_GENDER,
            XlsxParser.COL_ADDRESS,
            XlsxParser.COL_NOTE
    };

    /** Two valid example rows (VN sample data) so users copy the pattern. */
    private static final String[][] EXAMPLE_ROWS = {
            {"Nguyễn Văn An", "an.nguyen@example.com", "0901234567", "15/03/2010",
                    "MALE", "12 Lê Lợi, Quận 1, TP.HCM", "Lớp 9"},
            {"Trần Thị Bình", "binh.tran@example.com", "0912345678", "20/07/2011",
                    "FEMALE", "", ""}
    };

    /** Column widths in 1/256-of-a-char units (≈ char count × 256). */
    private static final int[] COLUMN_WIDTHS = {
            25 * 256, // name
            28 * 256, // email
            14 * 256, // phone
            16 * 256, // date_of_birth
            10 * 256, // gender
            36 * 256, // address
            20 * 256  // note
    };

    /** Per-column Vietnamese instructions (mirrors BR-BI-010..015). */
    private static final String[][] GUIDE_ROWS = {
            {"Cột", "Bắt buộc?", "Định dạng / Quy tắc"},
            {"name", "BẮT BUỘC", "Họ và tên học viên, 2-100 ký tự"},
            {"email", "BẮT BUỘC", "Email hợp lệ, tối đa 255 ký tự (vd: an.nguyen@example.com)"},
            {"phone", "Tùy chọn", "SĐT Việt Nam, định dạng 0xxxxxxxxx (10 số, bắt đầu bằng 0)"},
            {"date_of_birth", "Tùy chọn", "Ngày sinh định dạng dd/MM/yyyy (vd: 15/03/2010), không ở tương lai"},
            {"gender", "Tùy chọn", "MALE hoặc FEMALE (không phân biệt hoa thường)"},
            {"address", "Tùy chọn", "Địa chỉ, tối đa 1000 ký tự"},
            {"note", "Tùy chọn", "Ghi chú tự do"}
    };

    /**
     * Builds the blank import template xlsx.
     *
     * @return xlsx bytes ready to stream back to the client as an attachment
     */
    public byte[] generateTemplate() {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            CellStyle headerStyle = buildHeaderStyle(workbook);
            buildDataSheet(workbook, headerStyle);
            buildGuideSheet(workbook, headerStyle);

            workbook.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            log.error("Failed to generate bulk-import template xlsx", e);
            throw new BulkImportParseException(
                    "Không tạo được file template mẫu: " + e.getMessage(), e);
        }
    }

    private CellStyle buildHeaderStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.LIGHT_YELLOW.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return style;
    }

    private void buildDataSheet(Workbook workbook, CellStyle headerStyle) {
        Sheet sheet = workbook.createSheet(DATA_SHEET_NAME);

        // Header row (row 0) — bold + highlighted.
        Row header = sheet.createRow(0);
        for (int c = 0; c < HEADERS.length; c++) {
            Cell cell = header.createCell(c);
            cell.setCellValue(HEADERS[c]);
            cell.setCellStyle(headerStyle);
            sheet.setColumnWidth(c, COLUMN_WIDTHS[c]);
        }

        // Example data rows (rows 1..N) — all written as strings to preserve
        // leading-zero phone numbers + dd/MM/yyyy date format verbatim.
        for (int r = 0; r < EXAMPLE_ROWS.length; r++) {
            Row row = sheet.createRow(r + 1);
            String[] values = EXAMPLE_ROWS[r];
            for (int c = 0; c < values.length; c++) {
                row.createCell(c).setCellValue(values[c]);
            }
        }

        // Freeze the header row so it stays visible while scrolling.
        sheet.createFreezePane(0, 1);
    }

    private void buildGuideSheet(Workbook workbook, CellStyle headerStyle) {
        Sheet sheet = workbook.createSheet(GUIDE_SHEET_NAME);
        sheet.setColumnWidth(0, 18 * 256);
        sheet.setColumnWidth(1, 14 * 256);
        sheet.setColumnWidth(2, 60 * 256);

        for (int r = 0; r < GUIDE_ROWS.length; r++) {
            Row row = sheet.createRow(r);
            String[] cols = GUIDE_ROWS[r];
            for (int c = 0; c < cols.length; c++) {
                Cell cell = row.createCell(c);
                cell.setCellValue(cols[c]);
                if (r == 0) {
                    cell.setCellStyle(headerStyle);
                }
            }
        }
        sheet.createFreezePane(0, 1);
    }
}
