#!/usr/bin/env bash
#
# fetch-secrets.sh — Phase 1 BETA Secrets Manager → /etc/kite/.env populator
#
# Fetches secrets from AWS Secrets Manager (using EC2 instance profile,
# no static keys) and writes them into /etc/kite/.env for docker-compose.production.yml.
#
# Run on kh-backend EC2 BEFORE `docker compose up`.
# Run via SSM session OR as part of deploy-prod.sh.
#
# Per .claude/rules/agent-aws-access.md §2.2: get-secret-value is Tier 2
# (always-confirm) — but on EC2 with instance profile + secretsmanager:GetSecretValue
# scoped to kitehub/production/* this is the legitimate runtime path. Agent
# does NOT run this; it runs on EC2 as part of bootstrap.
#
# Required EC2 instance profile permissions (provisioned by terraform):
#   secretsmanager:GetSecretValue on arn:aws:secretsmanager:*:*:secret:kitehub/production/*
#   secretsmanager:DescribeSecret on same scope

set -euo pipefail

REGION="ap-southeast-1"
ENV_FILE="/etc/kite/.env"
LOG="${LOG:-/var/log/kite-bootstrap.log}"

log() { echo "[$(date -u +%FT%TZ)] $*" | tee -a "$LOG"; }

# Ensure /etc/kite directory exists with restricted permissions
sudo mkdir -p /etc/kite
sudo chown root:docker /etc/kite
sudo chmod 0750 /etc/kite

log "Fetching Phase 1 BETA secrets from Secrets Manager..."

fetch_secret() {
  local name="$1"
  local field="${2:-}"  # optional JSON field for json secrets

  local value
  value=$(aws secretsmanager get-secret-value \
    --secret-id "kitehub/production/${name}" \
    --region "$REGION" \
    --query SecretString --output text 2>/dev/null) || {
    log "WARN: Secret kitehub/production/${name} not found OR access denied"
    return 1
  }

  if [[ -n "$field" ]]; then
    echo "$value" | jq -r ".$field"
  else
    echo "$value"
  fi
}

# Fetch all required secrets
DB_PAYLOAD=$(fetch_secret db-password)
DB_USERNAME=$(echo "$DB_PAYLOAD" | jq -r .username)
DB_PASSWORD=$(echo "$DB_PAYLOAD" | jq -r .password)
DB_HOST=$(echo "$DB_PAYLOAD" | jq -r .host)
DB_PORT=$(echo "$DB_PAYLOAD" | jq -r .port)
DB_NAME=$(echo "$DB_PAYLOAD" | jq -r .dbname)

JWT_SECRET=$(fetch_secret jwt-secret)
ENCRYPTION_KEY=$(fetch_secret encryption-key)

# RabbitMQ creds (populated by populate-secrets.sh — may be empty if not yet run)
if RMQ_PAYLOAD=$(fetch_secret rabbitmq-default-creds 2>/dev/null); then
  RMQ_USER=$(echo "$RMQ_PAYLOAD" | jq -r .username 2>/dev/null || echo "")
  RMQ_PASS=$(echo "$RMQ_PAYLOAD" | jq -r .password 2>/dev/null || echo "")
fi
if [[ -z "${RMQ_USER:-}" || "$RMQ_USER" == "null" ]]; then
  log "WARN: rabbitmq-default-creds empty — generating ephemeral creds (run populate-secrets.sh + redeploy for persistence)"
  RMQ_USER="kite_admin_$(openssl rand -hex 4)"
  RMQ_PASS=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
fi

# Resend (from GitHub Secret, not Secrets Manager — Stream A pivot per ADR-025)
# kh-backend EC2 reads from a separate location; for Phase 1 BETA, allow optional
RESEND_API_KEY="${RESEND_API_KEY:-}"

# Write .env file
sudo tee "$ENV_FILE" > /dev/null <<ENVEOF
# Generated by fetch-secrets.sh — DO NOT EDIT BY HAND
# Regenerate: bash scripts/fetch-secrets.sh
# Generated at: $(date -u +%FT%TZ)

# Image version (set by deploy-prod.sh)
KITE_VERSION=${KITE_VERSION:-v0.9.0-beta-staging.8}

# Database (RDS — Phase 2.3 outputs)
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

# Redis (self-hosted on EC2)
REDIS_HOST=kite-redis
REDIS_PORT=6379
REDIS_PASSWORD=
SPRING_DATA_REDIS_HOST=kite-redis
SPRING_DATA_REDIS_PORT=6379

# RabbitMQ (self-hosted on EC2)
RABBITMQ_USER=${RMQ_USER}
RABBITMQ_PASS=${RMQ_PASS}
SPRING_RABBITMQ_HOST=kite-rabbitmq
SPRING_RABBITMQ_PORT=5672
SPRING_RABBITMQ_USERNAME=${RMQ_USER}
SPRING_RABBITMQ_PASSWORD=${RMQ_PASS}

# Auth secrets
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_MASTER_KEY=${ENCRYPTION_KEY}

# Email (Resend)
RESEND_API_KEY=${RESEND_API_KEY}

# Region pinning
AWS_REGION=ap-southeast-1
ENVEOF

sudo chown root:docker "$ENV_FILE"
sudo chmod 0640 "$ENV_FILE"

log "Wrote ${ENV_FILE} ($(wc -l < <(sudo cat "$ENV_FILE")) lines)"
log "Secrets fetch complete"
