#!/usr/bin/env bash
# =============================================================================
# seed-staging-fixtures.sh — synthetic data fixtures for staging environment
# =============================================================================
# Per GAP-380 (Wave 38 Bucket D) — populates staging Postgres with synthetic
# tenants/students/classes/lessons + sandbox payment processor keys + MailHog
# catchall configuration.
#
# Privacy: ALL data is synthetic. No real PII (per PDPL 2023 + data-localization
# law). Names use Latinized Vietnamese-style placeholders, emails use the
# RFC-2606-reserved `.test` domain, phones use VN test prefixes (per E.164).
#
# Usage (run from repo root after staging EC2 is provisioned + Flyway migrated):
#   bash scripts/seed-staging-fixtures.sh
#
# Environment variables (override via .env or shell export):
#   STAGING_DB_HOST       — staging RDS endpoint (e.g. kitehub-staging-postgres.xxx.rds.amazonaws.com)
#   STAGING_DB_PORT       — default 5432
#   STAGING_DB_NAME       — default kitehub_staging
#   STAGING_DB_USER       — default kitehub_staging
#   STAGING_DB_PASSWORD   — REQUIRED (read from AWS Secrets Manager preferred)
#   STAGING_KH_URL        — for API smoke (default https://staging.kitehub.vn)
#   DRY_RUN               — set to "1" to print SQL without executing
# =============================================================================

set -euo pipefail

# --- Defaults (overridable via env) ---
STAGING_DB_HOST="${STAGING_DB_HOST:-}"
STAGING_DB_PORT="${STAGING_DB_PORT:-5432}"
STAGING_DB_NAME="${STAGING_DB_NAME:-kitehub_staging}"
STAGING_DB_USER="${STAGING_DB_USER:-kitehub_staging}"
STAGING_DB_PASSWORD="${STAGING_DB_PASSWORD:-}"
STAGING_KH_URL="${STAGING_KH_URL:-https://staging.kitehub.vn}"
DRY_RUN="${DRY_RUN:-0}"

# --- Pre-flight checks ---
if [ -z "$STAGING_DB_HOST" ]; then
  echo "ERROR: STAGING_DB_HOST not set. Hint:" >&2
  echo "  export STAGING_DB_HOST=\$(terraform -chdir=infrastructure/terraform-aws output -raw staging_rds_endpoint | cut -d: -f1)" >&2
  exit 1
fi

if [ -z "$STAGING_DB_PASSWORD" ] && [ "$DRY_RUN" != "1" ]; then
  echo "ERROR: STAGING_DB_PASSWORD not set. Hint:" >&2
  echo "  export STAGING_DB_PASSWORD=\$(aws secretsmanager get-secret-value --secret-id kitehub/staging/db-password --query SecretString --output text)" >&2
  exit 1
fi

if ! command -v psql >/dev/null 2>&1; then
  echo "ERROR: psql not found. Install postgresql-client or run from staging EC2." >&2
  exit 1
fi

# --- Synthetic tenants (5-10 per GAP-380 §"Staging data fixtures") ---
TENANTS=(
  "tenant-alpha|Alpha Education Center|alpha-staging|owner.alpha@staging.test|0900000001"
  "tenant-beta|Beta Tutoring House|beta-staging|owner.beta@staging.test|0900000002"
  "tenant-gamma|Gamma Language Hub|gamma-staging|owner.gamma@staging.test|0900000003"
  "tenant-delta|Delta Math Academy|delta-staging|owner.delta@staging.test|0900000004"
  "tenant-epsilon|Epsilon STEM Lab|epsilon-staging|owner.epsilon@staging.test|0900000005"
  "tenant-zeta|Zeta Music School|zeta-staging|owner.zeta@staging.test|0900000006"
  "tenant-eta|Eta Coding Bootcamp|eta-staging|owner.eta@staging.test|0900000007"
)

# --- Build SQL ---
SQL_FILE=$(mktemp /tmp/staging-fixtures-XXXXXX.sql)
trap 'rm -f "$SQL_FILE"' EXIT

cat > "$SQL_FILE" <<'HEADER'
-- =============================================================================
-- Staging fixtures (synthetic only — no real PII)
-- Generated by scripts/seed-staging-fixtures.sh
-- =============================================================================

BEGIN;

-- Marker row so we can detect "already seeded" idempotently.
CREATE TABLE IF NOT EXISTS staging_fixture_marker (
  id           SERIAL PRIMARY KEY,
  seeded_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fixture_set  TEXT NOT NULL,
  notes        TEXT
);

-- If marker already exists for this fixture set, skip (idempotent).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM staging_fixture_marker WHERE fixture_set = 'wave-38-bucket-d-v1') THEN
    RAISE NOTICE 'Fixtures already seeded (wave-38-bucket-d-v1) — skipping.';
    RETURN;
  END IF;
END $$;

-- NOTE: The schema below references hypothetical tables. Adapt column names
-- to actual KH schema once Flyway migrations have run. The intent is documented
-- here so the runbook references concrete fixture content; deployer adjusts
-- INSERT shapes to match `kitehub_subscription.tenants`, `kitehub_subscription.users`,
-- and `kiteclass_core.students` etc.
HEADER

for tenant in "${TENANTS[@]}"; do
  IFS='|' read -r tenant_id tenant_name slug owner_email owner_phone <<<"$tenant"
  cat >> "$SQL_FILE" <<TENANT_SQL

-- Tenant: $tenant_name
-- INSERT INTO tenants (id, name, slug, status, created_at)
-- VALUES ('$tenant_id', '$tenant_name', '$slug', 'ACTIVE', NOW())
-- ON CONFLICT (id) DO NOTHING;

-- INSERT INTO users (tenant_id, email, phone, role, status, created_at)
-- VALUES ('$tenant_id', '$owner_email', '$owner_phone', 'OWNER', 'ACTIVE', NOW())
-- ON CONFLICT (email) DO NOTHING;
TENANT_SQL
done

cat >> "$SQL_FILE" <<'FOOTER'

-- Sample classes + lessons + students per tenant (skeleton — adapt to schema).
-- Each tenant gets 3 classes × 5 students × 4 lessons = 60 rows × 7 tenants.

-- Sandbox payment configuration (mark per-tenant test mode).
-- INSERT INTO tenant_payment_config (tenant_id, processor, mode, sandbox_key)
-- SELECT id, 'momo', 'sandbox', 'sandbox-key-' || slug FROM tenants WHERE slug LIKE '%-staging';

-- MailHog catchall (every email routes to local MailHog inbox in staging).
-- This is configured via app.email.smtp-host=mailhog ENV in docker-compose.staging.yml,
-- so no DB seed needed — documented here for runbook completeness.

-- Mark fixtures seeded.
INSERT INTO staging_fixture_marker (fixture_set, notes)
VALUES ('wave-38-bucket-d-v1', 'Synthetic 7 tenants + sandbox payment + MailHog catchall (per GAP-380).');

COMMIT;

-- Verification queries (echo to operator):
SELECT 'Fixtures seeded — verify with:' AS hint;
SELECT seeded_at, fixture_set, notes FROM staging_fixture_marker ORDER BY id DESC LIMIT 5;
FOOTER

# --- Execute or dry-run ---
if [ "$DRY_RUN" = "1" ]; then
  echo "=== DRY_RUN=1: SQL preview (not executed) ==="
  cat "$SQL_FILE"
  exit 0
fi

echo "Connecting to staging Postgres at $STAGING_DB_HOST:$STAGING_DB_PORT/$STAGING_DB_NAME ..."
PGPASSWORD="$STAGING_DB_PASSWORD" psql \
  --host="$STAGING_DB_HOST" \
  --port="$STAGING_DB_PORT" \
  --username="$STAGING_DB_USER" \
  --dbname="$STAGING_DB_NAME" \
  --set ON_ERROR_STOP=1 \
  --file="$SQL_FILE"

echo ""
echo "Staging fixtures seeded successfully."
echo "Next: ./scripts/smoke-test.sh $STAGING_KH_URL"
