#!/usr/bin/env bash
# ssl-cert-setup.sh — Provision Let's Encrypt cert for a domain via certbot HTTP-01.
#
# Usage:
#   sudo bash scripts/ssl-cert-setup.sh <domain> <admin-email>
#
# Example:
#   sudo bash scripts/ssl-cert-setup.sh beta.kitehub.vn admin@kitehub.vn
#
# Requirements:
#   - Run as root (or sudo) — certbot needs to bind port 80 + write to /etc/letsencrypt
#   - Port 80 must be reachable on this host (Cloudflare proxy DISABLED during issuance — grey cloud)
#   - apt-based system (Debian/Ubuntu) — adapt for other distros
#   - nginx installed (renewal hook reloads it; comment out post-hook if not using nginx)
#
# Exit codes:
#   0 — cert issued (or already present + valid)
#   1 — invalid arguments
#   2 — certbot install failed
#   3 — cert issuance failed
#   4 — cron entry failed
#
# References:
#   - Let's Encrypt: https://letsencrypt.org/getting-started/
#   - certbot docs: https://eff-certbot.readthedocs.io/
#   - Project rule: .claude/rules/release-deploy-standard.md §3.1 Security
#   - Sister runbook: documents/05-guides/operations/dns-setup-runbook.md §2.4

set -euo pipefail

# ---- Args ----
if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <domain> <admin-email>" >&2
  echo "Example: $0 beta.kitehub.vn admin@kitehub.vn" >&2
  exit 1
fi

DOMAIN="$1"
EMAIL="$2"

# Basic validation — fail-fast on typos
if ! [[ "$DOMAIN" =~ ^[a-z0-9.-]+\.[a-z]{2,}$ ]]; then
  echo "ERROR: invalid domain format: $DOMAIN" >&2
  exit 1
fi

if ! [[ "$EMAIL" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
  echo "ERROR: invalid email format: $EMAIL" >&2
  exit 1
fi

# Must be root for /etc/letsencrypt write + port 80 bind
if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: this script must run as root (try: sudo $0 ...)" >&2
  exit 1
fi

# ---- Install certbot ----
if ! command -v certbot >/dev/null 2>&1; then
  echo "==> Installing certbot via apt..."
  if ! apt-get update -qq; then
    echo "ERROR: apt-get update failed" >&2
    exit 2
  fi
  if ! apt-get install -y -qq certbot; then
    echo "ERROR: certbot install via apt failed; try snap fallback:" >&2
    echo "  snap install --classic certbot && ln -s /snap/bin/certbot /usr/bin/certbot" >&2
    exit 2
  fi
fi

CERTBOT_VERSION="$(certbot --version 2>&1 | awk '{print $2}')"
echo "==> certbot version: $CERTBOT_VERSION"

# ---- Issue or skip ----
CERT_PATH="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"

if [[ -f "$CERT_PATH" ]]; then
  # Check days-to-expiry — if >30, skip; else renew
  EXPIRY_DAYS=$(openssl x509 -in "$CERT_PATH" -noout -checkend 2592000 >/dev/null 2>&1 && echo "ok" || echo "renew")
  if [[ "$EXPIRY_DAYS" == "ok" ]]; then
    echo "==> Cert for $DOMAIN already valid >30 days; skipping issuance"
  else
    echo "==> Cert for $DOMAIN expires <30 days; renewing..."
    if ! certbot renew --quiet --cert-name "$DOMAIN"; then
      echo "ERROR: cert renewal failed for $DOMAIN" >&2
      exit 3
    fi
  fi
else
  echo "==> Requesting new cert for $DOMAIN via HTTP-01 challenge..."
  echo "    NOTE: Cloudflare proxy must be DISABLED (grey cloud) during issuance."
  echo "    Port 80 must be reachable from public internet."

  if ! certbot certonly \
      --standalone \
      --non-interactive \
      --agree-tos \
      --email "$EMAIL" \
      --domain "$DOMAIN" \
      --rsa-key-size 4096 \
      --keep-until-expiring; then
    echo "ERROR: certbot certonly failed for $DOMAIN" >&2
    echo "  Common causes:" >&2
    echo "  - Port 80 not reachable (firewall, Cloudflare proxy still on)" >&2
    echo "  - DNS A record not propagated (check: dig +short $DOMAIN @8.8.8.8)" >&2
    echo "  - Rate limit (5 failed validations / hour per Let's Encrypt)" >&2
    exit 3
  fi
fi

# ---- Cron weekly renewal ----
CRON_FILE="/etc/cron.d/kitehub-certbot-renew"
if [[ ! -f "$CRON_FILE" ]]; then
  echo "==> Installing weekly cron renewal at $CRON_FILE"
  cat > "$CRON_FILE" <<'CRON_EOF'
# Kitehub: Let's Encrypt cert renewal — weekly Sunday 03:00 UTC
# Generated by scripts/ssl-cert-setup.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

0 3 * * 0 root certbot renew --quiet --post-hook "systemctl reload nginx 2>/dev/null || true" >> /var/log/kitehub-certbot.log 2>&1
CRON_EOF
  chmod 644 "$CRON_FILE"
  if ! systemctl restart cron 2>/dev/null && ! service cron restart 2>/dev/null; then
    echo "WARN: cron service restart failed; cron entry installed but daemon not reloaded" >&2
    # Don't exit — cron will pick up the file on next minute boundary
  fi
fi

# ---- Webhook notify (optional — only if NTFY_TOPIC env set) ----
if [[ -n "${NTFY_TOPIC:-}" ]]; then
  curl -fsS -X POST "https://ntfy.sh/${NTFY_TOPIC}" \
    -H "Title: SSL cert provisioned" \
    -d "Domain: $DOMAIN — cert at $CERT_PATH (cron: $CRON_FILE)" \
    >/dev/null 2>&1 || echo "WARN: ntfy notify failed (non-blocking)"
fi

# ---- Summary ----
echo ""
echo "===================================================================="
echo "  SSL cert setup complete for: $DOMAIN"
echo "===================================================================="
echo "  Certificate: $CERT_PATH"
echo "  Private key: /etc/letsencrypt/live/${DOMAIN}/privkey.pem"
echo "  Renewal cron: $CRON_FILE"
echo ""
echo "  Next steps:"
echo "  1. Configure nginx (or your reverse proxy) to use the cert"
echo "  2. Re-enable Cloudflare proxy (orange cloud) on $DOMAIN"
echo "  3. Verify: curl -I https://$DOMAIN"
echo "===================================================================="

exit 0
