package com.kiteclass.core.module.invoice.entity;

import com.kiteclass.core.common.constant.InvoiceStatus;
import com.kiteclass.core.common.entity.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Index;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import org.hibernate.annotations.BatchSize;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Invoice entity representing a billing invoice for a student.
 *
 * <p>Manages invoice lifecycle including:
 * <ul>
 *   <li>Invoice items (tuition, materials, fees)</li>
 *   <li>Adjustments (discounts, late fees)</li>
 *   <li>Payment tracking</li>
 *   <li>Auto-calculation of totals</li>
 * </ul>
 *
 * <p>Business Rules:
 * <ul>
 *   <li>BR-INV-001: Auto-generate invoice from enrollment</li>
 *   <li>BR-INV-002: Calculate total = subtotal + adjustments</li>
 *   <li>BR-INV-003: Track payment status (SENT → PARTIAL → PAID)</li>
 *   <li>BR-INV-004: balanceDue = total - amountPaid (computed)</li>
 *   <li>BR-INV-005: One invoice per enrollment (enforced by unique constraint)</li>
 * </ul>
 *
 * @author KiteClass Team
 * @since 2.8.0
 */
@Entity
@Table(
        name = "invoices",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_invoices_instance_number",
                        columnNames = {"instance_id", "invoice_number"}
                ),
                // One invoice per (tenant, enrollment, billing month). Supersedes the
                // V79 single-column uk_invoices_enrollment so an enrollment can carry one
                // recurring invoice per month (GAP-297). The production migration V93
                // declares this index with NULLS NOT DISTINCT + a partial WHERE clause to
                // preserve the legacy "one auto-invoice per enrollment" guarantee for the
                // enrollment-time auto-invoice path (billing_month = NULL); Hibernate DDL
                // (test-only ddl-auto) cannot express those qualifiers, but batch invoices
                // always carry a non-null billing_month so uniqueness holds in tests too.
                @UniqueConstraint(
                        name = "uk_invoices_enrollment_month",
                        columnNames = {"instance_id", "enrollment_id", "billing_month"}
                )
        },
        indexes = {
                @Index(name = "idx_invoices_instance", columnList = "instance_id"),
                @Index(name = "idx_invoices_student", columnList = "student_id"),
                @Index(name = "idx_invoices_class", columnList = "class_id"),
                @Index(name = "idx_invoices_status", columnList = "status"),
                @Index(name = "idx_invoices_due_date", columnList = "due_date"),
                @Index(name = "idx_invoices_enrollment", columnList = "enrollment_id"),
                @Index(name = "idx_invoices_billing_month", columnList = "billing_month"),
                @Index(name = "idx_invoices_deleted", columnList = "deleted")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invoice extends BaseEntity {

    /**
     * Unique invoice number.
     * Format: INV-YYYY-NNNNNN (e.g., INV-2026-000001)
     * Generated by InvoiceNumberGenerator.
     */
    @Column(name = "invoice_number", nullable = false, length = 50)
    private String invoiceNumber;

    /**
     * Foreign key to student.
     * Required, must reference an existing student.
     */
    @Column(name = "student_id", nullable = false)
    private Long studentId;

    /**
     * Foreign key to class.
     * Optional, null for invoices not linked to a class.
     */
    @Column(name = "class_id")
    private Long classId;

    /**
     * Foreign key to enrollment.
     * One invoice per enrollment (auto-created from enrollment event).
     */
    @Column(name = "enrollment_id")
    private Long enrollmentId;

    /**
     * Billing month for recurring monthly invoices (GAP-297).
     *
     * <p>Set to the first day of the billed month (e.g. {@code 2026-05-01} for
     * "May 2026") by the batch monthly invoice generation flow. Combined with
     * {@code enrollment_id} + {@code instance_id} it enforces idempotency — one
     * invoice per enrollment per month (unique constraint
     * {@code uk_invoices_enrollment_month}).
     *
     * <p>NULL for one-off auto-invoices created at enrollment time.
     */
    @Column(name = "billing_month")
    private LocalDate billingMonth;

    /**
     * Invoice status.
     * Defaults to DRAFT, transitions based on payment.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    @Builder.Default
    private InvoiceStatus status = InvoiceStatus.DRAFT;

    /**
     * Issue date of invoice.
     * Defaults to current date when invoice is created.
     */
    @Column(name = "issue_date", nullable = false)
    @Builder.Default
    private LocalDate issueDate = LocalDate.now();

    /**
     * Payment due date.
     * Required, determines overdue status.
     */
    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    /**
     * Start date of billing period.
     * For class enrollments, typically class start date.
     */
    @Column(name = "period_start", nullable = false)
    private LocalDate periodStart;

    /**
     * End date of billing period.
     * For class enrollments, typically class end date.
     */
    @Column(name = "period_end", nullable = false)
    private LocalDate periodEnd;

    /**
     * Subtotal before adjustments.
     * Sum of all invoice items.
     * Calculated automatically in @PrePersist/@PreUpdate.
     */
    @Column(name = "subtotal", nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal subtotal = BigDecimal.ZERO;

    /**
     * Discount amount (legacy field - retained for compatibility).
     * Prefer using InvoiceAdjustment for new discounts.
     */
    @Column(name = "discount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal discount = BigDecimal.ZERO;

    /**
     * Total amount after adjustments.
     * total = subtotal + sum(adjustments)
     * Calculated automatically in @PrePersist/@PreUpdate.
     */
    @Column(name = "total", nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal total = BigDecimal.ZERO;

    /**
     * Amount already paid towards this invoice.
     * Updated by Payment Module (future PR).
     */
    @Column(name = "amount_paid", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal amountPaid = BigDecimal.ZERO;

    /**
     * Timestamp when invoice was fully paid.
     * Set automatically when status changes to PAID.
     */
    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    /**
     * Additional notes for the invoice.
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Invoice items (line items).
     * Cascade ALL - items are part of invoice lifecycle.
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true)
    @BatchSize(size = 20)
    @Builder.Default
    private List<InvoiceItem> items = new ArrayList<>();

    /**
     * Invoice adjustments (discounts, fees).
     * Cascade ALL - adjustments are part of invoice lifecycle.
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true)
    @BatchSize(size = 20)
    @Builder.Default
    private List<InvoiceAdjustment> adjustments = new ArrayList<>();

    /**
     * Adds an invoice item to this invoice.
     * Sets bidirectional relationship.
     *
     * @param item the item to add
     */
    public void addItem(InvoiceItem item) {
        items.add(item);
        item.setInvoice(this);
    }

    /**
     * Removes an invoice item from this invoice.
     *
     * @param item the item to remove
     */
    public void removeItem(InvoiceItem item) {
        items.remove(item);
        item.setInvoice(null);
    }

    /**
     * Adds an adjustment to this invoice.
     * Sets bidirectional relationship.
     *
     * @param adjustment the adjustment to add
     */
    public void addAdjustment(InvoiceAdjustment adjustment) {
        adjustments.add(adjustment);
        adjustment.setInvoice(this);
    }

    /**
     * Removes an adjustment from this invoice.
     *
     * @param adjustment the adjustment to remove
     */
    public void removeAdjustment(InvoiceAdjustment adjustment) {
        adjustments.remove(adjustment);
        adjustment.setInvoice(null);
    }

    /**
     * Calculates invoice totals before persist/update.
     * Implements BR-INV-002: total = subtotal + adjustments.
     */
    @PrePersist
    @PreUpdate
    public void calculateTotals() {
        // Subtotal = sum of all item amounts
        this.subtotal = items.stream()
                .map(InvoiceItem::getAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add)
                .setScale(2, RoundingMode.HALF_UP);

        // Total adjustments (negative for discounts, positive for fees)
        BigDecimal totalAdjustments = adjustments.stream()
                .map(InvoiceAdjustment::getAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add)
                .setScale(2, RoundingMode.HALF_UP);

        // Total = subtotal + adjustments
        this.total = subtotal.add(totalAdjustments)
                .setScale(2, RoundingMode.HALF_UP);

        // Balance due = total - amount paid
        BigDecimal balanceDue = total.subtract(amountPaid)
                .setScale(2, RoundingMode.HALF_UP);

        // Update status based on balance
        updateStatus(balanceDue);
    }

    /**
     * Updates invoice status based on balance due.
     * Implements BR-INV-003: payment status transitions.
     *
     * @param balanceDue the current balance due
     */
    private void updateStatus(BigDecimal balanceDue) {
        // Don't change if already in final state
        if (status.isFinal()) {
            return;
        }

        // Fully paid
        if (balanceDue.compareTo(BigDecimal.ZERO) <= 0 &&
            amountPaid.compareTo(BigDecimal.ZERO) > 0) {
            this.status = InvoiceStatus.PAID;
            if (this.paidAt == null) {
                this.paidAt = LocalDateTime.now();
            }
        } else if (amountPaid.compareTo(BigDecimal.ZERO) > 0) {
            // Partially paid
            this.status = InvoiceStatus.PARTIAL;
        } else if (dueDate != null && LocalDate.now().isAfter(dueDate) &&
                   status != InvoiceStatus.DRAFT) {
            // Overdue
            this.status = InvoiceStatus.OVERDUE;
        }
    }

    /**
     * Gets the computed balance due (total - amountPaid).
     * This is computed at runtime, not stored.
     *
     * @return the balance due
     */
    public BigDecimal getBalanceDue() {
        return total.subtract(amountPaid).setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Checks if invoice can accept payment.
     *
     * @return true if status allows payment
     */
    public boolean canPay() {
        return status.canPay();
    }

    /**
     * Checks if invoice can be cancelled.
     *
     * @return true if status allows cancellation
     */
    public boolean canCancel() {
        return status.canCancel();
    }
}
